include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [".github/**", "build/**"]
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    - always_declare_return_types
    - always_use_package_imports
    - avoid_empty_else
    - avoid_print
    - cancel_subscriptions
    - constant_identifier_names
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - library_names
    - library_prefixes
    - no_duplicate_case_values
    - null_closures
    - prefer_final_fields
    - prefer_generic_function_type_aliases
    - type_annotate_public_apis
    - prefer_const_constructors
    - prefer_final_in_for_each
    - prefer_final_locals
